### ISSUE TITLE
[vault-secrets-webhook] pod mutation with multiple imagePullSecrets if first secret not found

### ISSUE THREAD

**Issue by alexey-ban** [bank-vaults/bank-vaults#1269]
**Describe the bug**:
K8s is able to pull images using the provided pull secrets, even if one of them doesn't exist

_vault-secrets-webhook_ picks the first listed imagePullSecret and broke if it _not found_

**Expected behaviour**:
_vault-secrets-webhook_ should attempt all listed imagePullSecrets to find the one that works.

**Steps to reproduce the bug**:
1. Create deployment with 2  imagePullSecrets:
```yaml
    imagePullSecrets:
    - name: registry1
    - name: registry2
```
2. Create only second (registry2) with valid credentials

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.18.9-eks-d1db3c
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17):  1.11.3
- Install method (e.g. helm or static manifests): helm 
- Logs from the misbehaving component (and any other relevant logs):
```
time="2021-02-22T21:21:03Z" level=warning msg="no tracer active" app=vault-secrets-webhook
time="2021-02-22T21:21:03Z" level=warning msg="no tracer active" app=vault-secrets-webhook
time="2021-02-22T21:21:03Z" level=info msg="Listening on https://:8443" app=vault-secrets-webhook
time="2021-02-22T21:21:40Z" level=error msg="admission webhook error: secrets \"registry1\" not found" app=vault-secrets-webhook
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bonifaido** [comment]
Hi @alexey-ban, which version of the webhook do you use?

**Comment by alexey-ban** [comment]
Hi @bonifaido  1.11.3

**Comment by bonifaido** [comment]
Hi, I just found that we have an upstream issue here in the go-containerregistry library that checks the container registries: https://github.com/google/go-containerregistry/issues/723

**Comment by dkulchinsky** [comment]
Hey folks, We're struggling with a similar issue that was originally reported in https://github.com/banzaicloud/bank-vaults/issues/1232

In our case, we have multiple `imagePullSecrets` defined that indeed exist and are correct (the reason is because same Pod has containers coming from different internal repos that have different secrets).

How in this scenario, VSW is only able to pull images for the registry whose secret is the first in the `imagePullSecrets` list, if the image is in the registry whose secret is 2nd - it fails to pull the image and mutation is not performed.

**Comment by dkulchinsky** [comment]
Hey @bonifaido 👋🏼 

I realize this is an upstream issue and looks like not something that can be easily fixed (although the PR that introduced the "bug" is really strange).

We are impacted by this due to our internal container registry having different secrets for different projects (namespace) in the registry.

Do you think there's anything that can be done in VSW to address this?

**Comment by csatib02** [comment]
Hey,

Can someone verify that this issue still present as of today?
