### ISSUE TITLE
[vault-secrets-webhook] When using configMapMutation the variables of vault-secrets-webhook prevails over pod annotations

### ISSUE THREAD

**Issue by ichasco-heytrade** [bank-vaults/bank-vaults#1291]
Hi,

When deploying the webhook with HELM, enabling `configMapMutation` the variables:
```
VAULT_ROLE: vault-secrets-webhook
VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
VAULT_PATH: kubernetes
```
must be defined in vault-secrets-webhook It can't not be possible to resolve the secrets of configmaps by the annotations defined in the pod which is using that configmap?

```
vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
vault.security.banzaicloud.io/vault-role: Service1
vault.security.banzaicloud.io/vault-path: kubernetes
```

And if these variables are defined in the vault-secrets-webhook pod, when resolving the secrets of the rest pods, is possible to use the annotations of the pod which uses that secrets. For the moment always prevails the variables of vault-secrets-webhook.

/kind bug

**Comment by csatib02** [comment]
Hey @ichasco-heytrade,

It's been a while since you posted this issue, sorry for the long delay.
It shouldn't be the case at the moment, since when the Webhook processes a resource, first it tries to parse the config from annotations, if a specific annotation is not present, then it uses the defaults set as env-vars.
Also give our new enhanced webhook a try: https://github.com/bank-vaults/secrets-webhook

I'm going to close this now, if you happened to encounter anymore issues, please open another ticket under the `secret-webhook` repo.
