### ISSUE TITLE
Error writing template file: open /vault/config/vault.json: permission denied 

### ISSUE THREAD

**Issue by ghost** [bank-vaults/bank-vaults#1308]
**Describe the bug**:

During the creation of pods, the configuration is generated from https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-raft.yaml#L127-L137 and written inside the pods in /vault/config/vault.json  

Vault continues to work fine, however strange error is visible some time after the creation of pods:

````
kubectl logs vault-0 -c config-templating

level=fatal msg="error writing template file: open /vault/config/vault.json: permission denied"
````

```
kubectl get pods | grep CrashLoopBackOff

vault-0                             0/3     Init:CrashLoopBackOff   21         16h
vault-1                             0/3     Init:CrashLoopBackOff   21         16h
vault-2                             0/3     Init:CrashLoopBackOff   21         16h
```
Is this normal or am I doing something wrong? 

P.S. And it seems that this behavior can be manually fixed (until the next pod reboot):

```
chmod 660 /vault/config/vault.json
```

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.19.7
- bank-vaults version (e.g. 0.4.17): 1.11.3
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by bonifaido** [comment]
This is very interesting since the volume this config is written to is a Kubernetes `emptyDir` with `Memory` as its medium.

```
  vault-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  1Mi
```

I think this could be related (maybe?), or other issues with the same context: https://github.com/rancher/rancher/issues/27278

**Comment by enggalilioo** [comment]
We have the same issue in our vault cluster, sometimes I had to change the permissions on the file to allow the init container (config-templating) to access the file
But since this is an EmptyDir, while doing any restart to the pod, I had recheck the permission 

`Defaulted container "vault" out of: vault, bank-vaults, prometheus-exporter, config-templating (init)
/ # ls -ltra /vault/config/vault.json
-rw-------    1 vault    vault          309 Sep 11 07:54 /vault/config/vault.json`
