### ISSUE TITLE
[vault-webhook-eks]-Unable to mutate pod

### ISSUE THREAD

**Issue by tvarade** [bank-vaults/bank-vaults#1392]
I have install vault webhook 1.12.0 on eks and when i tried to mutate pod with the help of annotation it wo t work.
No i it container spin up.
How to solve this?

**Comment by tvarade** [comment]
any update?

**Comment by csatib02** [comment]
Hi @tvarade,

It's been quite sometime since you posted this issue, and sorry for the delay.

Next time when you open an issue, please provide the following details to help us address it more efficiently: a clear and concise description of the problem, step-by-step instructions on how to reproduce the issue, what you expected to happen versus what actually happened, details about the environment in which the issue occurred (such as software version, and any relevant configurations), and any screenshots or log files that might help us understand the issue better.
Since then, we've already added an issue template so it will be easier and more structured to provide these details.

I'm going to close this issue, if you need any further assistance please open another issue under the relevant project.
