### ISSUE TITLE
How to download the CLI binary?

### ISSUE THREAD

**Issue by alwaysastudent** [bank-vaults/bank-vaults#1431]
The documentation says 

> To grab the CLI binary go to the releases page and download it.

But the [releases](https://github.com/banzaicloud/bank-vaults/releases) page only has source tarballs up there.

Can you please help with where we could download the CLI binary directly from?

**Comment by csatib02** [comment]
Hey @alwaysastudent,

It's been a while since you created this issue, and I'm sorry that you had to wait for this long...
It might be not actual for you but I will just go ahead and answer your question. :)

We've updated the Getting started page in our [documentation](https://bank-vaults.dev/docs/installing/#install-the-cli-tool), and you should be able to find a method that fits your use-case.

Alternatively if all else falls, you can clone the repo, and use the appropriate makefile command to build the CLI yourself.
