### ISSUE TITLE
Consider dropping Viper

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/bank-vaults#2032]
Due to #1990 we had to revert to an older Viper version.

After a brief look at the code, I'm not entirely sure we need Viper.

We only load files with Viper and use it's watch feature to some extent, but those can probably be replaced by just fsnotify.

If we really don't use any other configuration source (flag, env var, etc), I vote for dropping Viper from BV at this time.

**Comment by ramizpolic** [comment]
I think it is beneficial that we answer the following questions first and make a decision based on that:
- Do we need to continue supporting env variables (either statically or dynamically)? 
- Are file changes relevant to us?
- Do we need to support both env and file changes?

If we opt-in to remove Viper completely, I am slightly worried on how we would handle these cases, especially the native loading from different config source sync locations (env, config, flags).

However, I do think that there are improvement possibilities as is, for example:
- using concrete types for specific config groups (e.g. GCP config group) rather than single-item fetchers (viper.GetString...)
- native viper hot reloading feature in favour of bare fsnotify

**Comment by ramizpolic** [comment]
Didn't have time to work on this. Should not be too complex for someone to pick up. If not, then it will be resolved once I'm back.

**Comment by ramizpolic** [comment]
After a short investigation, here's what I discovered:
- The CLI uses various sources to load data (flags and env variables)
- Vault configs are only loaded from files and watched with fsnotify.  The upside is not having to worry about filetypes when reading into structs since this is done automatically.

Therefore, even though we can drop Viper, I am worried about dropping support for env vars on CLI side. I am not sure if this is a good idea as there may be instances where CLI is being run only via env configs. Alternatively, we can consider only dropping Viper for vault files. I'd be happy to hear your input @sagikazarmark

**Comment by sagikazarmark** [comment]
@ramizpolic given file loaded configs are never merged withe env vars or flags, I'd vote for loading and parsing files without Viper.
